<template>
  <view class="page-container">
    <NavBar
      title="编辑场馆"
      :showBack="true"
      backgroundColor="#ff6b35"
      titleColor="#ffffff"
      :showBorder="false"
      @left-click="goBack"
    />
    <view class="page-body" :style="{ paddingTop: navBarHeight + 'px' }">
      <scroll-view scroll-y class="scroll-content">
        <view v-if="loadingDetail" class="loading-box">
          <text class="loading-text">加载中...</text>
        </view>

        <template v-else>
          <view class="card">
            <view class="form-group">
              <text class="form-label">场馆名称</text>
              <input class="form-input" v-model="form.name" placeholder="请输入场馆名称" />
            </view>
            <view class="form-group">
              <text class="form-label">场馆类型</text>
              <picker :range="venueTypes" :value="venueTypeIndex" @change="onTypeChange">
                <view class="form-input picker-input">{{ form.type || '请选择类型' }}</view>
              </picker>
            </view>
            <view class="form-group">
              <text class="form-label">小时单价（元）</text>
              <input class="form-input" v-model="form.price" type="digit" placeholder="请输入价格" />
            </view>
            <view class="form-group">
              <text class="form-label">营业时间</text>
              <view class="time-row">
                <picker mode="time" :value="form.openTime" @change="e => form.openTime = e.detail.value">
                  <view class="form-input time-input">{{ form.openTime || '开始时间' }}</view>
                </picker>
                <text class="time-sep">~</text>
                <picker mode="time" :value="form.closeTime" @change="e => form.closeTime = e.detail.value">
                  <view class="form-input time-input">{{ form.closeTime || '结束时间' }}</view>
                </picker>
              </view>
            </view>
            <view class="form-group">
              <text class="form-label">联系电话</text>
              <input class="form-input" v-model="form.contactPhone" type="number" placeholder="请输入联系电话" />
            </view>
            <view class="form-group">
              <text class="form-label">场馆图片</text>
              <view class="image-upload-row">
                <view class="upload-btn" @click="chooseImage">
                  <image v-if="form.coverImage" :src="form.coverImage" class="preview-image" mode="aspectFill" />
                  <text v-else class="upload-icon">+</text>
                </view>
              </view>
            </view>
            <view class="form-group">
              <text class="form-label">位置</text>
              <input class="form-input" v-model="form.location" placeholder="如: A区3楼" />
            </view>
            <view class="form-group">
              <text class="form-label">场馆介绍</text>
              <textarea class="form-textarea" v-model="form.description" placeholder="请输入场馆介绍" />
            </view>
            <view class="form-group">
              <text class="form-label">设施标签（逗号分隔）</text>
              <input class="form-input" v-model="facilityTagsStr" placeholder="如: 木地板,空调,淋浴" />
            </view>
            <view class="form-group switch-group">
              <text class="form-label">支持拼场</text>
              <switch :checked="form.supportSharing" color="#ff6b35" @change="e => form.supportSharing = e.detail.value" />
            </view>
            <view class="form-group">
              <text class="form-label">自动生成排期天数</text>
              <picker :range="autoDaysOptions" range-key="label" :value="autoDaysIndex" @change="onAutoDaysChange">
                <view class="form-input picker-input">未来{{ form.autoGenerateDays }}天</view>
              </picker>
            </view>
          </view>

          <view class="save-btn" :class="{ disabled: saving }" @click="handleSave">
            <text class="save-btn-text">{{ saving ? '保存中...' : '保存' }}</text>
          </view>

          <view class="delete-btn" @click="handleDelete">
            <text class="delete-btn-text">删除场馆</text>
          </view>
        </template>
      </scroll-view>
    </view>
  </view>
</template>

<script>
import NavBar from '@/components/NavBar.vue'
import { useAdminVenuesStore } from '@/stores/admin-venues.js'

export default {
  components: { NavBar },

  data() {
    return {
      venuesStore: null,
      navBarHeight: 0,
      venueId: null,
      loadingDetail: false,
      saving: false,
      facilityTagsStr: '',
      venueTypes: ['篮球', '羽毛球', '网球', '足球', '乒乓球', '游泳', '其他'],
      autoDaysOptions: [{ label: '未来7天', value: 7 }, { label: '未来15天', value: 15 }],
      form: {
        name: '',
        type: '篮球',
        price: '',
        openTime: '09:00',
        closeTime: '22:00',
        contactPhone: '',
        coverImage: '',
        location: '',
        description: '',
        supportSharing: false,
        autoGenerateDays: 7
      }
    }
  },

  computed: {
    venueTypeIndex() {
      const idx = this.venueTypes.indexOf(this.form.type)
      return idx >= 0 ? idx : 0
    },
    autoDaysIndex() {
      return this.autoDaysOptions.findIndex(o => o.value === this.form.autoGenerateDays) || 0
    }
  },

  onLoad(options) {
    this.venueId = options.id
    this.venuesStore = useAdminVenuesStore()
    this.calcNavBarHeight()
    this.loadVenue()
  },

  methods: {
    calcNavBarHeight() {
      const sys = uni.getSystemInfoSync()
      this.navBarHeight = (sys.statusBarHeight || 0) + 44
    },

    goBack() {
      uni.navigateBack()
    },

    async loadVenue() {
      if (!this.venueId) return
      this.loadingDetail = true
      try {
        const venue = await this.venuesStore.fetchVenueDetail(this.venueId)
        this.form = {
          name: venue.name || '',
          type: venue.type || '篮球',
          price: String(venue.price || ''),
          openTime: (venue.openTime || '09:00:00').substring(0, 5),
          closeTime: (venue.closeTime || '22:00:00').substring(0, 5),
          contactPhone: venue.contactPhone || '',
          coverImage: venue.coverImage || venue.image || '',
          location: venue.location || '',
          description: venue.description || '',
          supportSharing: venue.supportSharing || false,
          autoGenerateDays: venue.autoGenerateDays || 7
        }
        const tags = venue.facilityTags || venue.features || []
        this.facilityTagsStr = Array.isArray(tags) ? tags.join(',') : ''
      } catch (e) {
        uni.showToast({ title: e.message || '加载失败', icon: 'none' })
      } finally {
        this.loadingDetail = false
      }
    },

    onTypeChange(e) {
      this.form.type = this.venueTypes[e.detail.value]
    },

    onAutoDaysChange(e) {
      this.form.autoGenerateDays = this.autoDaysOptions[e.detail.value].value
    },

    chooseImage() {
      uni.chooseImage({
        count: 1,
        success: (res) => {
          this.form.coverImage = res.tempFilePaths[0]
        }
      })
    },

    validate() {
      if (!this.form.name.trim()) { uni.showToast({ title: '请输入场馆名称', icon: 'none' }); return false }
      if (!this.form.price) { uni.showToast({ title: '请输入价格', icon: 'none' }); return false }
      return true
    },

    async handleSave() {
      if (this.saving || !this.validate()) return
      this.saving = true

      const data = {
        id: Number(this.venueId),
        ...this.form,
        price: Number(this.form.price),
        facilityTags: this.facilityTagsStr.split(',').map(t => t.trim()).filter(Boolean),
        openTime: this.form.openTime,
        closeTime: this.form.closeTime
      }

      try {
        await this.venuesStore.saveVenue(data)
        uni.showToast({ title: '更新成功', icon: 'success' })
        setTimeout(() => uni.navigateBack(), 1500)
      } catch (e) {
        uni.showToast({ title: e.message || '更新失败', icon: 'none' })
      } finally {
        this.saving = false
      }
    },

    handleDelete() {
      uni.showModal({
        title: '确认删除',
        content: '确定要删除该场馆吗？此操作不可撤销。',
        success: async (res) => {
          if (!res.confirm) return
          try {
            await this.venuesStore.removeVenue(Number(this.venueId))
            uni.showToast({ title: '删除成功', icon: 'success' })
            setTimeout(() => uni.navigateBack(), 1500)
          } catch (e) {
            uni.showToast({ title: e.message || '删除失败', icon: 'none' })
          }
        }
      })
    }
  }
}
</script>

<style lang="scss" scoped>
.page-container {
  min-height: 100vh;
  background: #f5f5f5;
}

.page-body {
  min-height: 100vh;
}

.scroll-content {
  padding: 24rpx;
  padding-bottom: 60rpx;
}

.card {
  background: #ffffff;
  border-radius: 24rpx;
  padding: 28rpx;
  margin-bottom: 24rpx;
  box-shadow: 0 4rpx 16rpx rgba(0, 0, 0, 0.04);
}

.form-group {
  margin-bottom: 32rpx;
  &:last-child { margin-bottom: 0; }
}

.form-label {
  display: block;
  font-size: 28rpx;
  font-weight: 500;
  color: #303133;
  margin-bottom: 16rpx;
}

.form-input {
  width: 100%;
  height: 88rpx;
  line-height: 88rpx;
  padding: 0 24rpx;
  border: 2rpx solid #dcdfe6;
  border-radius: 16rpx;
  font-size: 28rpx;
  background: #ffffff;
  color: #303133;
  box-sizing: border-box;
}

.picker-input { color: #606266; }

.form-textarea {
  width: 100%;
  padding: 24rpx;
  border: 2rpx solid #dcdfe6;
  border-radius: 16rpx;
  font-size: 28rpx;
  min-height: 160rpx;
  box-sizing: border-box;
}

.time-row {
  display: flex;
  align-items: center;
  gap: 16rpx;
  picker { flex: 1; }
}

.time-input { text-align: center; }
.time-sep { color: #909399; font-size: 28rpx; }

.switch-group {
  display: flex;
  justify-content: space-between;
  align-items: center;
  .form-label { margin-bottom: 0; }
}

.image-upload-row { display: flex; }

.upload-btn {
  width: 160rpx;
  height: 160rpx;
  background: #f5f7fa;
  border: 2rpx dashed #dcdfe6;
  border-radius: 16rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}

.upload-icon { font-size: 64rpx; color: #909399; }
.preview-image { width: 100%; height: 100%; }

.save-btn {
  width: 100%;
  height: 88rpx;
  line-height: 88rpx;
  text-align: center;
  background: #ff6b35;
  border-radius: 44rpx;
  margin-bottom: 24rpx;
  &.disabled { background: #cccccc; }
}

.save-btn-text { color: #ffffff; font-size: 32rpx; font-weight: 600; }

.delete-btn {
  width: 100%;
  height: 88rpx;
  line-height: 88rpx;
  text-align: center;
  background: #ffffff;
  border: 2rpx solid #fa3534;
  border-radius: 44rpx;
  margin-bottom: 40rpx;
}

.delete-btn-text { color: #fa3534; font-size: 32rpx; font-weight: 600; }

.loading-box { text-align: center; padding: 120rpx 0; }
.loading-text { font-size: 28rpx; color: #909399; }
</style>
